package entities;
// Generated Oct 25, 2016 9:57:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Customer generated by hbm2java
 */
public class Customer  implements java.io.Serializable {


     private Integer idCustomer;
     private String name;
     private String phone;
     private Date dateOfBirth;
     private Set invoices = new HashSet(0);

    public Customer() {
    }

	
    public Customer(String name) {
        this.name = name;
    }
    public Customer(String name, String phone, Date dateOfBirth, Set invoices) {
       this.name = name;
       this.phone = phone;
       this.dateOfBirth = dateOfBirth;
       this.invoices = invoices;
    }
   
    public Integer getIdCustomer() {
        return this.idCustomer;
    }
    
    public void setIdCustomer(Integer idCustomer) {
        this.idCustomer = idCustomer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


