package entities;
// Generated Oct 25, 2016 9:57:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Employee generated by hbm2java
 */
public class Employee  implements java.io.Serializable {


     private Integer idEmployee;
     private String username;
     private String password;
     private String name;
     private String role;
     private String email;
     private String sex;
     private String phone;
     private Date dateOfBirth;
     private String image;
     private Set invoices = new HashSet(0);

    public Employee() {
    }

	
    public Employee(String username, String password, String name, String role, String sex, Date dateOfBirth) {
        this.username = username;
        this.password = password;
        this.name = name;
        this.role = role;
        this.sex = sex;
        this.dateOfBirth = dateOfBirth;
    }
    public Employee(String username, String password, String name, String role, String email, String sex, String phone, Date dateOfBirth, String image, Set invoices) {
       this.username = username;
       this.password = password;
       this.name = name;
       this.role = role;
       this.email = email;
       this.sex = sex;
       this.phone = phone;
       this.dateOfBirth = dateOfBirth;
       this.image = image;
       this.invoices = invoices;
    }
   
    public Integer getIdEmployee() {
        return this.idEmployee;
    }
    
    public void setIdEmployee(Integer idEmployee) {
        this.idEmployee = idEmployee;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getSex() {
        return this.sex;
    }
    
    public void setSex(String sex) {
        this.sex = sex;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public Date getDateOfBirth() {
        return this.dateOfBirth;
    }
    
    public void setDateOfBirth(Date dateOfBirth) {
        this.dateOfBirth = dateOfBirth;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getInvoices() {
        return this.invoices;
    }
    
    public void setInvoices(Set invoices) {
        this.invoices = invoices;
    }




}


