package entities;
// Generated Oct 25, 2016 9:57:21 PM by Hibernate Tools 4.3.1



/**
 * InvoiceDetail generated by hbm2java
 */
public class InvoiceDetail  implements java.io.Serializable {


     private Integer idDetail;
     private Invoice invoice;
     private Product product;
     private int quantity;
     private double price;

    public InvoiceDetail() {
    }

    public InvoiceDetail(Invoice invoice, Product product, int quantity, double price) {
       this.invoice = invoice;
       this.product = product;
       this.quantity = quantity;
       this.price = price;
    }
   
    public Integer getIdDetail() {
        return this.idDetail;
    }
    
    public void setIdDetail(Integer idDetail) {
        this.idDetail = idDetail;
    }
    public Invoice getInvoice() {
        return this.invoice;
    }
    
    public void setInvoice(Invoice invoice) {
        this.invoice = invoice;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(int quantity) {
        this.quantity = quantity;
    }
    public double getPrice() {
        return this.price;
    }
    
    public void setPrice(double price) {
        this.price = price;
    }




}


