package entities;
// Generated Oct 25, 2016 9:57:21 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Invoice generated by hbm2java
 */
public class Invoice  implements java.io.Serializable {


     private Integer idInvoice;
     private Customer customer;
     private Employee employee;
     private Date initialDate;
     private String state;
     private Set invoiceDetails = new HashSet(0);

    public Invoice() {
    }

	
    public Invoice(Customer customer, Employee employee, Date initialDate) {
        this.customer = customer;
        this.employee = employee;
        this.initialDate = initialDate;
    }
    public Invoice(Customer customer, Employee employee, Date initialDate, String state, Set invoiceDetails) {
       this.customer = customer;
       this.employee = employee;
       this.initialDate = initialDate;
       this.state = state;
       this.invoiceDetails = invoiceDetails;
    }
   
    public Integer getIdInvoice() {
        return this.idInvoice;
    }
    
    public void setIdInvoice(Integer idInvoice) {
        this.idInvoice = idInvoice;
    }
    public Customer getCustomer() {
        return this.customer;
    }
    
    public void setCustomer(Customer customer) {
        this.customer = customer;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Date getInitialDate() {
        return this.initialDate;
    }
    
    public void setInitialDate(Date initialDate) {
        this.initialDate = initialDate;
    }
    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


