package entities;
// Generated Oct 25, 2016 9:57:21 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Product generated by hbm2java
 */
public class Product  implements java.io.Serializable {


     private Integer idProduct;
     private Category category;
     private Manufacturer manufacturer;
     private String name;
     private Integer quantity;
     private double unitPrice;
     private String unit;
     private String image;
     private Set invoiceDetails = new HashSet(0);

    public Product() {
    }

	
    public Product(Category category, Manufacturer manufacturer, String name, double unitPrice) {
        this.category = category;
        this.manufacturer = manufacturer;
        this.name = name;
        this.unitPrice = unitPrice;
    }
    public Product(Category category, Manufacturer manufacturer, String name, Integer quantity, double unitPrice, String unit, String image, Set invoiceDetails) {
       this.category = category;
       this.manufacturer = manufacturer;
       this.name = name;
       this.quantity = quantity;
       this.unitPrice = unitPrice;
       this.unit = unit;
       this.image = image;
       this.invoiceDetails = invoiceDetails;
    }
   
    public Integer getIdProduct() {
        return this.idProduct;
    }
    
    public void setIdProduct(Integer idProduct) {
        this.idProduct = idProduct;
    }
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }
    public Manufacturer getManufacturer() {
        return this.manufacturer;
    }
    
    public void setManufacturer(Manufacturer manufacturer) {
        this.manufacturer = manufacturer;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Integer getQuantity() {
        return this.quantity;
    }
    
    public void setQuantity(Integer quantity) {
        this.quantity = quantity;
    }
    public double getUnitPrice() {
        return this.unitPrice;
    }
    
    public void setUnitPrice(double unitPrice) {
        this.unitPrice = unitPrice;
    }
    public String getUnit() {
        return this.unit;
    }
    
    public void setUnit(String unit) {
        this.unit = unit;
    }
    public String getImage() {
        return this.image;
    }
    
    public void setImage(String image) {
        this.image = image;
    }
    public Set getInvoiceDetails() {
        return this.invoiceDetails;
    }
    
    public void setInvoiceDetails(Set invoiceDetails) {
        this.invoiceDetails = invoiceDetails;
    }




}


