/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entities.Manufacturer;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import model.ManufacturerDAO;
import model.ManufacturerTableModel;

/**
 *
 * @author Chi Nguyen T-rex
 */
public class BrandManagement extends javax.swing.JPanel {

    private ManufacturerDAO manufacturerDAO = new ManufacturerDAO();
    private ListSelectionModel listSelectionModel;
    private ListSelectionListener listSelectionListener;

    /**
     * Creates new form CategoryManagement
     */
    public BrandManagement() {
        initComponents();
        brandTable.setModel(new ManufacturerTableModel());

        brandTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        listSelectionModel = brandTable.getSelectionModel();
        listSelectionModel.addListSelectionListener(listSelectionListener = new ListSelectionListener() {

            @Override
            public void valueChanged(ListSelectionEvent e) {
                if (e.getValueIsAdjusting()) {
                    System.out.println(listSelectionModel.getMinSelectionIndex());
                    return;
                }

                txtBrand.setText((String) brandTable.getValueAt(listSelectionModel.getMinSelectionIndex(), 2));
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lblBrandWarn = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtBrand = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        btnAddBrand = new javax.swing.JButton();
        btnDeleteBrand = new javax.swing.JButton();
        btnUpdateBrand = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        brandTable = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(153, 255, 255));
        jPanel1.setLayout(new java.awt.GridLayout(5, 1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        lblBrandWarn.setForeground(new java.awt.Color(255, 0, 0));
        lblBrandWarn.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(338, 338, 338)
                .addComponent(lblBrandWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(408, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblBrandWarn, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Tên thương hiệu:");

        txtBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 415, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(405, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(txtBrand)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        btnAddBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnAddBrand.setText("Add");
        btnAddBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddBrandActionPerformed(evt);
            }
        });

        btnDeleteBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnDeleteBrand.setText("Delete");
        btnDeleteBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteBrandActionPerformed(evt);
            }
        });

        btnUpdateBrand.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnUpdateBrand.setText("Update");
        btnUpdateBrand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateBrandActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(152, 152, 152)
                .addComponent(btnAddBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnUpdateBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnDeleteBrand, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(402, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddBrand, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDeleteBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(btnUpdateBrand, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel1.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 970, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel7);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(1, 1));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        brandTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(brandTable);

        jPanel2.add(jScrollPane1);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddBrandActionPerformed
        listSelectionModel.removeListSelectionListener(listSelectionListener);

        String name = txtBrand.getText();
        if (name.equals("")) {
            lblBrandWarn.setText("Bạn hãy nhập tên thương hiệu");
        } else {
            lblBrandWarn.setText("");
            txtBrand.setText("");
            manufacturerDAO.addOrUpdateManufacturer(new Manufacturer(name));
            brandTable.setModel(new ManufacturerTableModel());
        }
        listSelectionModel.addListSelectionListener(listSelectionListener);
    }//GEN-LAST:event_btnAddBrandActionPerformed

    private void btnDeleteBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteBrandActionPerformed
        listSelectionModel.removeListSelectionListener(listSelectionListener);
        int select = brandTable.getSelectedRow();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Bạn cần chọn một dòng để xóa!", "Deletion", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Manufacturer manufacturer = new Manufacturer((String) brandTable.getValueAt(select, 2));
            manufacturer.setIdManufacturer((int) brandTable.getValueAt(select, 1));

            if (manufacturerDAO.deleteManufacturer(manufacturer)) {
                txtBrand.setText("");
                JOptionPane.showMessageDialog(this, "Xóa thành công!", "Deletion", JOptionPane.INFORMATION_MESSAGE);
                brandTable.setModel(new ManufacturerTableModel());
            } else {
                JOptionPane.showMessageDialog(this, "Không có danh mục này!", "Deletion", JOptionPane.INFORMATION_MESSAGE);

            }

        }
        listSelectionModel.addListSelectionListener(listSelectionListener);
    }//GEN-LAST:event_btnDeleteBrandActionPerformed

    private void btnUpdateBrandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateBrandActionPerformed
        listSelectionModel.removeListSelectionListener(listSelectionListener);
        
        int select = brandTable.getSelectedRow();
        if (select == -1) {
            JOptionPane.showMessageDialog(this, "Bạn hãy chọn dòng cần update!", "Update", JOptionPane.INFORMATION_MESSAGE);
        } else {
            Manufacturer manufacturer = new Manufacturer(txtBrand.getText());
            manufacturer.setIdManufacturer((int) brandTable.getValueAt(select, 1));

            if (manufacturerDAO.addOrUpdateManufacturer(manufacturer)) {
                txtBrand.setText("");
                JOptionPane.showMessageDialog(this, "Update thành công!", "Update", JOptionPane.INFORMATION_MESSAGE);
                brandTable.setModel(new ManufacturerTableModel());
            } else {
                JOptionPane.showMessageDialog(this, "Update thất bại!", "Update", JOptionPane.INFORMATION_MESSAGE);
            }

        }

        listSelectionModel.addListSelectionListener(listSelectionListener);
    }//GEN-LAST:event_btnUpdateBrandActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable brandTable;
    private javax.swing.JButton btnAddBrand;
    private javax.swing.JButton btnDeleteBrand;
    private javax.swing.JButton btnUpdateBrand;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBrandWarn;
    private javax.swing.JTextField txtBrand;
    // End of variables declaration//GEN-END:variables
}
