/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import de.javasoft.plaf.synthetica.SyntheticaPlainLookAndFeel;
import javax.swing.JFrame;
import javax.swing.UIManager;

/**
 *
 * @author Chi Nguyen T-rex
 */
public class Login extends javax.swing.JFrame {
    private static LoginPanel loginPanel;
    private static RecoverPassword recoverPassword;
    private static JFrame mainFrame;

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        mainFrame = this;
        loginPanel = new LoginPanel();
        mainPanel.add(loginPanel);
        setLocationRelativeTo(null);
        this.setResizable(false);
        setVisible(true);
    }
    
    public static void setLoginTitle(String title) {
        lblLoginTitle.setText(title);
    }
    
    public static JFrame getMainFrame() {
        return mainFrame;
    }
    
    public static void removeLoginPanel() {
        mainPanel.remove(loginPanel);
    }
    
     public static void addLoginPanel() {
        mainPanel.add(loginPanel);
    }
    
    public static void setRecoverPassword() {
        recoverPassword = new RecoverPassword();
    }
    
    public static void removeRecoverPassword() {
        mainPanel.remove(recoverPassword);
    }
    
    public static void addRecoverPassword() {
        mainPanel.add(recoverPassword);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblLoginIcon = new javax.swing.JLabel();
        lblLoginTitle = new javax.swing.JLabel();
        mainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(0, 0));
        setSize(new java.awt.Dimension(800, 415));

        jPanel1.setBackground(new java.awt.Color(0, 102, 255));

        lblLoginIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login.png"))); // NOI18N

        lblLoginTitle.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblLoginTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblLoginTitle.setText("Let's log-in");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblLoginIcon)
                .addGap(251, 251, 251)
                .addComponent(lblLoginTitle)
                .addContainerGap(358, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblLoginIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblLoginTitle)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setPreferredSize(new java.awt.Dimension(800, 319));
        mainPanel.setLayout(new java.awt.GridLayout(1, 1));
        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        UIManager.put("Synthetica.text.antialias", Boolean.TRUE);
        try {
            UIManager.setLookAndFeel(new SyntheticaPlainLookAndFeel());
            //UIManager.setLookAndFeel(new SyntheticaStandardLookAndFeel());
        } 
        catch (Exception e) {
            System.out.println("Error");
        }
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            mainFrame = new Login();
            mainFrame.setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoginIcon;
    private static javax.swing.JLabel lblLoginTitle;
    private static javax.swing.JPanel mainPanel;
    // End of variables declaration//GEN-END:variables
}
