/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.Font;
import javax.swing.ButtonModel;
import javax.swing.JTabbedPane;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;

/**
 *
 * @author Chi Nguyen T-rex
 */
public class ManagerPanel extends javax.swing.JPanel {

    private JTabbedPane mainTabbedPane;

    /**
     * Creates new form SalePanel
     */
    public ManagerPanel() {
        initComponents();
        mainTabbedPane = new JTabbedPane();
        mainTabbedPane.setFocusable(true);
        mainTabbedPane.setFont(new Font("Tahoma", Font.PLAIN, 14));
        righttPanel.add(mainTabbedPane);

        leftPanel.setSize(230, 557);
        righttPanel.setSize(970, 557);

        // Create hover effect for button
        btnEmployeeManager.getModel().addChangeListener(new ChangeListener() {

            @Override
            public void stateChanged(ChangeEvent e) {
                ButtonModel model = (ButtonModel) e.getSource();
                if (model.isRollover()) {
                    btnEmployeeManager.setForeground(new Color(0, 102, 255));
                } else {
                    btnEmployeeManager.setForeground(new Color(0, 0, 0));
                }
            }
        });

        

 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        tbnCategoryToolBar = new javax.swing.JButton();
        btnBrandToolBar = new javax.swing.JButton();
        btnProductToolBar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tbnRemoveTab = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnEmployeeManager = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        nullPanel = new javax.swing.JPanel();
        righttPanel = new javax.swing.JPanel();

        setBackground(new java.awt.Color(51, 255, 255));
        setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        tbnCategoryToolBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/won-24.png"))); // NOI18N
        tbnCategoryToolBar.setToolTipText("Quản lý danh mục");
        tbnCategoryToolBar.setFocusable(false);
        tbnCategoryToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbnCategoryToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbnCategoryToolBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnCategoryToolBarActionPerformed(evt);
            }
        });
        jToolBar1.add(tbnCategoryToolBar);

        btnBrandToolBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/blockchain-24.png"))); // NOI18N
        btnBrandToolBar.setToolTipText("Quản lý thương hiệu");
        btnBrandToolBar.setFocusable(false);
        btnBrandToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBrandToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnBrandToolBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrandToolBarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnBrandToolBar);

        btnProductToolBar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add_camera-24.png"))); // NOI18N
        btnProductToolBar.setToolTipText("Quản lý sản phẩm");
        btnProductToolBar.setFocusable(false);
        btnProductToolBar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnProductToolBar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnProductToolBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductToolBarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProductToolBar);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/about_us_female-24.png"))); // NOI18N
        jButton4.setToolTipText("Quản lý tài khoản");
        jButton4.setFocusable(false);
        jButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jButton4);

        tbnRemoveTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/minus-24.png"))); // NOI18N
        tbnRemoveTab.setToolTipText("Đóng Tab đang chọn");
        tbnRemoveTab.setFocusable(false);
        tbnRemoveTab.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tbnRemoveTab.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        tbnRemoveTab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tbnRemoveTabActionPerformed(evt);
            }
        });
        jToolBar1.add(tbnRemoveTab);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/unfriend_female-24.png"))); // NOI18N
        jButton6.setToolTipText("Log out");
        jButton6.setFocusable(false);
        jButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton6);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/cancel-24.png"))); // NOI18N
        jButton7.setToolTipText("Thoát chương trình");
        jButton7.setFocusable(false);
        jButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton7);

        add(jToolBar1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new java.awt.BorderLayout(4, 0));

        leftPanel.setBackground(new java.awt.Color(255, 255, 255));
        leftPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        leftPanel.setLayout(new java.awt.GridLayout(2, 1));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new java.awt.GridLayout(7, 1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Quản lý cửa hàng");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        btnEmployeeManager.setBackground(new java.awt.Color(255, 255, 255));
        btnEmployeeManager.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEmployeeManager.setText("Quản lý nhân sự");
        btnEmployeeManager.setBorder(null);
        btnEmployeeManager.setBorderPainted(false);
        btnEmployeeManager.setFocusPainted(false);
        btnEmployeeManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmployeeManagerActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnEmployeeManager)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEmployeeManager)
                .addContainerGap())
        );

        jPanel2.add(jPanel4);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel5);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel6);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel8);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 47, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel9);

        leftPanel.add(jPanel2);

        nullPanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout nullPanelLayout = new javax.swing.GroupLayout(nullPanel);
        nullPanel.setLayout(nullPanelLayout);
        nullPanelLayout.setHorizontalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 204, Short.MAX_VALUE)
        );
        nullPanelLayout.setVerticalGroup(
            nullPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 329, Short.MAX_VALUE)
        );

        leftPanel.add(nullPanel);

        jPanel1.add(leftPanel, java.awt.BorderLayout.LINE_START);

        righttPanel.setBackground(new java.awt.Color(255, 255, 255));
        righttPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        righttPanel.setLayout(new java.awt.GridLayout(1, 1));
        jPanel1.add(righttPanel, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEmployeeManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmployeeManagerActionPerformed
        mainTabbedPane.addTab("Quản lý nhân viên", null, new EmployeeManagement());
        int i = mainTabbedPane.getTabCount();
        mainTabbedPane.setSelectedIndex(i - 1);

    }//GEN-LAST:event_btnEmployeeManagerActionPerformed

    private void tbnRemoveTabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnRemoveTabActionPerformed
        if (mainTabbedPane.getTabCount() != 0) {
            mainTabbedPane.remove(mainTabbedPane.getSelectedIndex());
        }
    }//GEN-LAST:event_tbnRemoveTabActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        new Login();
        MainGUI.getMainFrameGUI().dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void tbnCategoryToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tbnCategoryToolBarActionPerformed

    }//GEN-LAST:event_tbnCategoryToolBarActionPerformed

    private void btnBrandToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrandToolBarActionPerformed

    }//GEN-LAST:event_btnBrandToolBarActionPerformed

    private void btnProductToolBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductToolBarActionPerformed

    }//GEN-LAST:event_btnProductToolBarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrandToolBar;
    private javax.swing.JButton btnEmployeeManager;
    private javax.swing.JButton btnProductToolBar;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel nullPanel;
    private javax.swing.JPanel righttPanel;
    private javax.swing.JButton tbnCategoryToolBar;
    private javax.swing.JButton tbnRemoveTab;
    // End of variables declaration//GEN-END:variables
}
